name: chat-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10  # hoặc đổi thành 3.11 nếu muốn
  - pip
  - faiss-cpu
  - pip:
      - fastapi
      - uvicorn
      - python-dotenv
      - authlib
      - motor
      - pymongo
      - python-multipart
      - ipykernel
      - itsdangerous
      - httpx
      - sentence-transformers