name: chat-env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10  # hoặc 3.11 nếu bạn muốn
  - pip
  - faiss-gpu
  - pip:
      - fastapi
      - uvicorn
      - python-dotenv
      - authlib
      - motor
      - pymongo
      - python-multipart
      - ipykernel
      - itsdangerous
      - httpx
      - sentence-transformers
      - bitsandbytes
      - datasets
      - loralib
      - einops
      - sentencepiece
      - torch>=2.0.0
      - git+https://github.com/huggingface/transformers.git
      - git+https://github.com/huggingface/peft.git
      - git+https://github.com/huggingface/accelerate.git